// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/in-toto/archivista/ent/attributeassertion"
	"github.com/in-toto/archivista/ent/attributereport"
	"github.com/in-toto/archivista/ent/statement"
)

// AttributeReportCreate is the builder for creating a AttributeReport entity.
type AttributeReportCreate struct {
	config
	mutation *AttributeReportMutation
	hooks    []Hook
}

// AddAttributeIDs adds the "attributes" edge to the AttributeAssertion entity by IDs.
func (arc *AttributeReportCreate) AddAttributeIDs(ids ...int) *AttributeReportCreate {
	arc.mutation.AddAttributeIDs(ids...)
	return arc
}

// AddAttributes adds the "attributes" edges to the AttributeAssertion entity.
func (arc *AttributeReportCreate) AddAttributes(a ...*AttributeAssertion) *AttributeReportCreate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return arc.AddAttributeIDs(ids...)
}

// SetStatementID sets the "statement" edge to the Statement entity by ID.
func (arc *AttributeReportCreate) SetStatementID(id int) *AttributeReportCreate {
	arc.mutation.SetStatementID(id)
	return arc
}

// SetStatement sets the "statement" edge to the Statement entity.
func (arc *AttributeReportCreate) SetStatement(s *Statement) *AttributeReportCreate {
	return arc.SetStatementID(s.ID)
}

// Mutation returns the AttributeReportMutation object of the builder.
func (arc *AttributeReportCreate) Mutation() *AttributeReportMutation {
	return arc.mutation
}

// Save creates the AttributeReport in the database.
func (arc *AttributeReportCreate) Save(ctx context.Context) (*AttributeReport, error) {
	return withHooks(ctx, arc.sqlSave, arc.mutation, arc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (arc *AttributeReportCreate) SaveX(ctx context.Context) *AttributeReport {
	v, err := arc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (arc *AttributeReportCreate) Exec(ctx context.Context) error {
	_, err := arc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (arc *AttributeReportCreate) ExecX(ctx context.Context) {
	if err := arc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (arc *AttributeReportCreate) check() error {
	if _, ok := arc.mutation.StatementID(); !ok {
		return &ValidationError{Name: "statement", err: errors.New(`ent: missing required edge "AttributeReport.statement"`)}
	}
	return nil
}

func (arc *AttributeReportCreate) sqlSave(ctx context.Context) (*AttributeReport, error) {
	if err := arc.check(); err != nil {
		return nil, err
	}
	_node, _spec := arc.createSpec()
	if err := sqlgraph.CreateNode(ctx, arc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	arc.mutation.id = &_node.ID
	arc.mutation.done = true
	return _node, nil
}

func (arc *AttributeReportCreate) createSpec() (*AttributeReport, *sqlgraph.CreateSpec) {
	var (
		_node = &AttributeReport{config: arc.config}
		_spec = sqlgraph.NewCreateSpec(attributereport.Table, sqlgraph.NewFieldSpec(attributereport.FieldID, field.TypeInt))
	)
	if nodes := arc.mutation.AttributesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   attributereport.AttributesTable,
			Columns: []string{attributereport.AttributesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attributeassertion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := arc.mutation.StatementIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   attributereport.StatementTable,
			Columns: []string{attributereport.StatementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(statement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.statement_attributes_report = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AttributeReportCreateBulk is the builder for creating many AttributeReport entities in bulk.
type AttributeReportCreateBulk struct {
	config
	err      error
	builders []*AttributeReportCreate
}

// Save creates the AttributeReport entities in the database.
func (arcb *AttributeReportCreateBulk) Save(ctx context.Context) ([]*AttributeReport, error) {
	if arcb.err != nil {
		return nil, arcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(arcb.builders))
	nodes := make([]*AttributeReport, len(arcb.builders))
	mutators := make([]Mutator, len(arcb.builders))
	for i := range arcb.builders {
		func(i int, root context.Context) {
			builder := arcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AttributeReportMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, arcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, arcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, arcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (arcb *AttributeReportCreateBulk) SaveX(ctx context.Context) []*AttributeReport {
	v, err := arcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (arcb *AttributeReportCreateBulk) Exec(ctx context.Context) error {
	_, err := arcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (arcb *AttributeReportCreateBulk) ExecX(ctx context.Context) {
	if err := arcb.Exec(ctx); err != nil {
		panic(err)
	}
}
