// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/in-toto/archivista/ent/attributeassertion"
	"github.com/in-toto/archivista/ent/predicate"
)

// AttributeAssertionDelete is the builder for deleting a AttributeAssertion entity.
type AttributeAssertionDelete struct {
	config
	hooks    []Hook
	mutation *AttributeAssertionMutation
}

// Where appends a list predicates to the AttributeAssertionDelete builder.
func (aad *AttributeAssertionDelete) Where(ps ...predicate.AttributeAssertion) *AttributeAssertionDelete {
	aad.mutation.Where(ps...)
	return aad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (aad *AttributeAssertionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, aad.sqlExec, aad.mutation, aad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (aad *AttributeAssertionDelete) ExecX(ctx context.Context) int {
	n, err := aad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (aad *AttributeAssertionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(attributeassertion.Table, sqlgraph.NewFieldSpec(attributeassertion.FieldID, field.TypeInt))
	if ps := aad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, aad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	aad.mutation.done = true
	return affected, err
}

// AttributeAssertionDeleteOne is the builder for deleting a single AttributeAssertion entity.
type AttributeAssertionDeleteOne struct {
	aad *AttributeAssertionDelete
}

// Where appends a list predicates to the AttributeAssertionDelete builder.
func (aado *AttributeAssertionDeleteOne) Where(ps ...predicate.AttributeAssertion) *AttributeAssertionDeleteOne {
	aado.aad.mutation.Where(ps...)
	return aado
}

// Exec executes the deletion query.
func (aado *AttributeAssertionDeleteOne) Exec(ctx context.Context) error {
	n, err := aado.aad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{attributeassertion.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (aado *AttributeAssertionDeleteOne) ExecX(ctx context.Context) {
	if err := aado.Exec(ctx); err != nil {
		panic(err)
	}
}
