-- Create "attribute_reports" table
CREATE TABLE "attribute_reports" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "statement_attributes_report" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "attribute_reports_statements_attributes_report" FOREIGN KEY ("statement_attributes_report") REFERENCES "statements" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "attribute_reports_statement_attributes_report_key" to table: "attribute_reports"
CREATE UNIQUE INDEX "attribute_reports_statement_attributes_report_key" ON "attribute_reports" ("statement_attributes_report");
-- Create "attribute_assertions" table
CREATE TABLE "attribute_assertions" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "attribute" character varying NOT NULL, "target" jsonb NULL, "conditions" jsonb NULL, "evidence" jsonb NULL, "attribute_report_attributes" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "attribute_assertions_attribute_reports_attributes" FOREIGN KEY ("attribute_report_attributes") REFERENCES "attribute_reports" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create index "attribute_assertions_attribute_key" to table: "attribute_assertions"
CREATE UNIQUE INDEX "attribute_assertions_attribute_key" ON "attribute_assertions" ("attribute");
